export const GET_COURSES_REQUEST = "GET_COURSES_REQUEST";
export const GET_COURSES_SUCCESS = "GET_COURSES_SUCCESS";
export const GET_COURSES_FAILURE = "GET_COURSES_FAILURE";


export const GET_COURSESBYCATEGORY_REQUEST = "GET_COURSESBYCATEGORY_REQUEST";
export const GET_COURSESBYCATEGORY_SUCCESS = "GET_COURSESBYCATEGORY_SUCCESS";
export const GET_COURSESBYCATEGORY_FAILURE = "GET_COURSESBYCATEGORY_FAILURE";

export const GET_ALL_COURSES_REQUEST = "GET_ALL_COURSES_REQUEST";
export const GET_ALL_COURSES_SUCCESS = "GET_ALL_COURSES_SUCCESS";
export const GET_ALL_COURSES_FAILURE = "GET_ALL_COURSES_FAILURE";



